micronaut:
    application:
        name: micronaut-jwt
    security:
      enabled: true
      endpoints:
        login:
          enabled: true
        oauth:
          enabled: true
      token:
        jwt:
          enabled: true
          signatures:
            secret:
              generator:
                secret: Up6KjbnEV4Hgfo75YM393QdQsK3Z0aTNBz0DoirrW+c

datasources:
    default:
        url: jdbc:postgresql://localhost:5432/micronaut_examples
        username: admin
        password: password
        driverClassName: org.postgresql.Driver

jpa:
    default:
        packages-to-scan:
        - 'com.mrpato.examples.micronaut.jwt.domain'
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
                show_sql: true